### ISSUE TITLE
Compile Error! Declaration of Egulias\EmailValidator\Validation\MessageIDValidation::getError()...

### ISSUE THREAD

**Issue by robert-pod-trak** [egulias/EmailValidator#307] opened 2022-01-12 12:29 UTC
Hi and congrats on this software,

Around October 2021 emails stopped sending at all.  Fuel PHP just gives it's "Ooops! Something went wrong".  On my dev site though I get the below even after removing and doing a composer re-install. :  

Compile Error!
ErrorException [ Compile Error ]:
Declaration of Egulias\EmailValidator\Validation\MessageIDValidation::getError() must be compatible with Egulias\EmailValidator\Validation\EmailValidation::getError(): Egulias\EmailValidator\Result\InvalidEmail

DOCROOT/fuel/vendor/egulias/email-validator/src/Validation/MessageIDValidation.php @ line 10

class MessageIDValidation implements EmailValidation
{
....

Backtrace
COREPATH/bootstrap.php @ line 80

Many thanks,
Robert

**Comment by egulias** [comment] 2022-01-14 15:42
Hi @robert-pod-trak 
Latest version show them both equal: 
https://github.com/egulias/EmailValidator/blob/3.x/src/Validation/EmailValidation.php#L26
https://github.com/egulias/EmailValidator/blob/3.x/src/Validation/MessageIDValidation.php#L47

The only difference is the docblock, missing in `MessageIDValidation` but that shouldn't give a compilation error.
Are you on the latest version?

**Comment by robert-pod-trak** [comment] 2022-01-14 17:54
v3.1.1 

elso get this  : 

Backtrace
COREPATH/bootstrap.php @ line 80
```
75        else
76        {
77            logger(\Fuel::L_ERROR, 'shutdown - ' . $e->getMessage()." in ".$e->getFile()." on ".$e->getLine());
78        }
79    }
80    return \Errorhandler::shutdown_handler();
81});
82
83set_exception_handler(function ($e)
84{
85    // reset the autoloader
```

my cpmoser installed.json : 
```
"name": "egulias/email-validator",
            "version": "3.1.1",
            "version_normalized": "3.1.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/egulias/EmailValidator.git",
                "reference": "c81f18a3efb941d8c4d2e025f6183b5c6d697307"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/egulias/EmailValidator/zipball/c81f18a3efb941d8c4d2e025f6183b5c6d697307",
                "reference": "c81f18a3efb941d8c4d2e025f6183b5c6d697307",
                "shasum": ""
            },
            "require": {
                "doctrine/lexer": "^1.2",
                "php": ">=7.2",
                "symfony/polyfill-intl-idn": "^1.15"
            },
            "require-dev": {
                "php-coveralls/php-coveralls": "^2.2",
                "phpunit/phpunit": "^8.5.8|^9.3.3",
                "vimeo/psalm": "^4"
            },
            "suggest": {
                "ext-intl": "PHP Internationalization Libraries are required to use the SpoofChecking validation"
            },
            "time": "2021-04-01T18:37:14+00:00",
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "3.0.x-dev"
                }
            },
            "installation-source": "dist",
            "autoload": {
                "psr-4": {
                    "Egulias\\EmailValidator\\": "src"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Eduardo Gulias Davis"
                }
            ],
            "description": "A library for validating emails against several RFCs",
            "homepage": "https://github.com/egulias/EmailValidator",
            "keywords": [
                "email",
                "emailvalidation",
                "emailvalidator",
                "validation",
                "validator"
            ],
            "support": {
                "issues": "https://github.com/egulias/EmailValidator/issues",
                "source": "https://github.com/egulias/EmailValidator/tree/3.1.1"
            },
            "funding": [
                {
                    "url": "https://github.com/egulias",
                    "type": "github"
                }
            ],
            "install-path": "../egulias/email-validator"
        },
```

Thanks

**Comment by robert-pod-trak** [comment] 2022-01-18 17:29
Hi again.  Have upgraded to 3.1.2 but to no avail.  May be a clash with SwiftMailer we also use in tandem?  Or, Possibly we need PHP over version 7.0?  Thanks, Robert

**Comment by egulias** [comment] 2022-02-02 18:17
Hi there. 
Thanks for the patience. You do need PHP >=7.2 https://github.com/egulias/EmailValidator/blob/3.x/composer.json#L16

**Comment by robert-pod-trak** [comment] 2022-02-03 10:27
Good morning,

Thanks.  Yes were working on upgrading our testing & staging  servers to 7.2.

Kind regards
Robert


p.s.  You can access our Dashboard<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdashboard.pod-trak.com%2Ftakefive&data=04%7C01%7Crobert.lambert%40pod-trak.com%7Ca29e86f804924351d53f08d9a52fabe8%7C80a3d42c059e408c936d6175543cb8bc%7C0%7C0%7C637722446431551406%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1E7dr3kjpXP9EtvYp0RYFMWHVG3p3OZ9h68wgSNNcGs%3D&reserved=0> on pretty much any mobile browser also.  Create, edit, close out & download.  We are adding the ability to create Site & Supervisor Inspections too soon.




Robert Lambert
Pod-Trak
Woodrow Way | Thames Trading Estate
| Irlam
| Manchester
| M44 6NN
Office:0161 518 4388
***@***.***
Mobile:07767115326
Web:www.pod-trak.com
Please consider the environment before printing this email.
DISCLAIMER: This email and any attachments are intended solely for the individual to whom it is addressed. Please contact the sender if you believe you have received this email in error. It is the recipient's responsibility to ensure that appropriate measures are in place to check for software viruses. Any opinions expressed are solely those of the author and do not necessarily represent those of Pod-Trak Ltd. 
Copyright © 2021 Pod-Trak Ltd, All rights reserved | Company Registered No. 6337165 | Registered VAT No. 885 7532 73 | UTR No. 1723128033 Registered Office: Crove House, 14 Aintree Road, Perivale, Middlesex, UB6 7LA | 0845 450 4190 | www.pod-trak.com

**Comment by egulias** [comment] 2022-02-04 20:32
Cool. Let me know so I can close the issue.

**Comment by fisharebest** [comment] 2022-03-21 14:51
I don't know if this helps identify the cause of *your* error, but I got the same error when installing an older version of an application on top of a newer version (without deleting the old files first).

The result was that I had the `MessageIDValidation` class from v3 present in an installation that used v2.

SymfonyMailer uses `class_exists(MessageIDValidation::class)`, which triggers the error.

**Closed as completed** 2022-06-12 15:41 UTC
